variable "prsaz1_name" {}
variable "prsaz2_name" {}
variable "db-sg-name" {}
variable "sg-name" {}
variable "rds-username" {}
variable "rds-password" {}
variable "db-name" {}
variable "rds-name" {}
variable "vpc_name" {}
variable "web-sg-name" {}